apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:zonex5/library-argocd.git
    targetRevision: HEAD
    path: microservices
  destination:
    server: https://kubernetes.default.svc
    namespace: ms
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true