apiVersion: v1
kind: Namespace
metadata:
  name: ms

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-a
  namespace: ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-a
  template:
    metadata:
      labels:
        app: ms-a
    spec:
      containers:
        - name: ms-a
          image: localhost:5000/ms-argocd-a:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ms-a
  namespace: ms
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
  selector:
    app: ms-a
