apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-a
  namespace: ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-a
  template:
    metadata:
      labels:
        app: ms-a
    spec:
      containers:
        - name: ms-a
          image: localhost:5000/ms-argocd-a:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080