apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq
  labels:
    istio-injection: disabled

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: rabbitmq
data:
  enabled_plugins: |
    [rabbitmq_management].

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:management-alpine
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "user"
        - name: RABBITMQ_DEFAULT_PASS
          value: "user"
        ports:
        - containerPort: 5672 
        - containerPort: 15672 
        volumeMounts:
        - name: config-volume
          mountPath: /etc/rabbitmq
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "380Mi"
            cpu: "500m"
      volumes:
      - name: config-volume
        configMap:
          name: rabbitmq-config

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  namespace: rabbitmq
spec:
  ports:
  - port: 5672
    targetPort: 5672
    name: amqp
  - port: 15672
    targetPort: 15672
    name: management
  selector:
    app: rabbitmq
