apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: localhost:5000/service-a:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080