# Deployment for postgres-sales
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-sales
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-sales
  template:
    metadata:
      labels:
        app: postgres-sales
    spec:
      containers:
        - name: postgres
          image: postgres:16.4-alpine3.20
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: db_sales
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "380Mi"
              cpu: "300m"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-sales-pvc
        - name: init-scripts
          configMap:
            name: postgres-init-scripts-sales

---
# PVC for postgres-sales
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-sales-pvc
  namespace: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
#Service for connection to postgres
apiVersion: v1
kind: Service
metadata:
  name: postgres-sales-svc
  namespace: postgres
spec:
  type: NodePort
  selector:
    app: postgres-sales
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30033
      