apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts-library
  namespace: postgres
data:
  init.sql: |
    -- Создание таблицы libraries
    CREATE TABLE libraries
    (
        id      serial
            CONSTRAINT libraries_pk
                PRIMARY KEY,
        name    varchar(150) NOT NULL
            CONSTRAINT libraries_name_unique
                UNIQUE,
        address varchar(250)
    );

    -- Создание таблицы stock
    CREATE TABLE stock
    (
        id         serial
            CONSTRAINT stock_pk
                PRIMARY KEY,
        id_library integer                 NOT NULL
            CONSTRAINT stock_libraries_id_fk
                REFERENCES libraries
                ON UPDATE CASCADE
                ON DELETE CASCADE,
        id_book    integer                 NOT NULL,
        quantity   integer       DEFAULT 0 NOT NULL,
        price      numeric(9, 2) DEFAULT 0 NOT NULL,
        CONSTRAINT stock_unique_library_book
            UNIQUE (id_library, id_book)
    );

    -- Создание представления library_stock_view
    CREATE OR REPLACE VIEW library_stock_view(id, id_library, name, address, id_book, quantity, price) AS
    SELECT DISTINCT s.id,
                    l.id AS id_library,
                    l.name,
                    l.address,
                    s.id_book,
                    s.quantity,
                    s.price
    FROM stock s
             JOIN libraries l ON l.id = s.id_library;

    -- Вставка данных в таблицу libraries
    INSERT INTO libraries (id, name, address)
    VALUES
        (1, 'New York Public Library', '476 5th Ave, New York, NY 10018, USA'),
        (2, 'British Library', '96 Euston Rd, London NW1 2DB, United Kingdom'),
        (3, 'Library of Congress', '101 Independence Ave SE, Washington, DC 20540, USA'),
        (4, 'Boston Public Library', '700 Boylston St, Boston, MA 02116, USA'),
        (5, 'Los Angeles Public Library', '630 W 5th St, Los Angeles, CA 90071, USA');

    -- Вставка данных в таблицу stock
    INSERT INTO stock (id, id_library, id_book, quantity, price)
    VALUES
        -- New York Public Library (id_library = 1)
        (1, 1, 1, 5, 25.99),
        (2, 1, 2, 3, 22.50),
        (3, 1, 3, 4, 24.75),
        (4, 1, 4, 2, 27.00),
        (5, 1, 5, 6, 26.50),
        (6, 1, 6, 7, 19.99),
        (7, 1, 7, 5, 18.75),
        (8, 1, 8, 4, 20.00),
        (9, 1, 9, 3, 22.00),
        (10, 1, 10, 2, 23.50),
        
        -- British Library (id_library = 2)
        (11, 2, 11, 5, 15.99),
        (12, 2, 12, 3, 18.50),
        (13, 2, 13, 4, 19.75),
        (14, 2, 14, 2, 20.00),
        (15, 2, 15, 6, 17.50),
        (16, 2, 16, 7, 14.99),
        (17, 2, 17, 5, 16.75),
        (18, 2, 18, 4, 15.00),
        (19, 2, 19, 3, 18.25),
        (20, 2, 20, 2, 19.50),
        
        -- Library of Congress (id_library = 3)
        (21, 3, 21, 5, 20.99),
        (22, 3, 22, 3, 19.50),
        (23, 3, 23, 4, 18.75),
        (24, 3, 24, 2, 17.50),
        (25, 3, 25, 6, 16.00),
        (26, 3, 26, 5, 14.99),
        (27, 3, 27, 3, 15.50),
        (28, 3, 28, 4, 16.25),
        (29, 3, 29, 2, 17.00),
        (30, 3, 30, 3, 18.00),
        
        -- Boston Public Library (id_library = 4)
        (31, 4, 31, 5, 13.99),
        (32, 4, 32, 3, 12.50),
        (33, 4, 33, 4, 14.75),
        (34, 4, 34, 2, 13.00),
        (35, 4, 35, 6, 15.50),
        (36, 4, 36, 5, 11.99),
        (37, 4, 37, 3, 12.50),
        (38, 4, 38, 4, 14.00),
        (39, 4, 39, 2, 13.75),
        (40, 4, 40, 3, 14.50),
        
        -- Los Angeles Public Library (id_library = 5)
        (41, 5, 41, 5, 19.99),
        (42, 5, 42, 3, 18.50),
        (43, 5, 43, 4, 20.75),
        (44, 5, 44, 2, 17.00),
        (45, 5, 45, 6, 19.50),
        (46, 5, 46, 5, 22.99),
        (47, 5, 47, 3, 21.50),
        (48, 5, 48, 4, 20.75),
        (49, 5, 49, 2, 19.00),
        (50, 5, 50, 3, 21.25),
        
        -- Library of Congress (id_library = 3)
        (51, 3, 55, 4, 23.00),
        (52, 3, 56, 5, 24.50),
        
        -- Boston Public Library (id_library = 4)
        (53, 4, 57, 6, 19.99),
        (54, 4, 58, 3, 18.75),
        
        -- Los Angeles Public Library (id_library = 5)
        (55, 5, 59, 4, 25.00),
        (56, 5, 60, 2, 22.50),
        (57, 5, 61, 5, 20.00),
        (58, 5, 62, 3, 21.75),
        (59, 5, 63, 4, 19.50),
        (60, 5, 64, 2, 18.25);

    -- Обновление последовательностей
    SELECT setval('libraries_id_seq', (SELECT MAX(id) FROM libraries));
    SELECT setval('stock_id_seq', (SELECT MAX(id) FROM stock));