# service-sales-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-service
  namespace: ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-service
  template:
    metadata:
      labels:
        app: sales-service
    spec:
      containers:
        - name: sales-service
          image: localhost:5000/sales-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-sales-svc.postgres.svc.cluster.local:5432/db_sales
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq-svc.rabbitmq.svc.cluster.local
            - name: SPRING_RABBITMQ_USERNAME
              value: user
            - name: SPRING_RABBITMQ_PASSWORD
              value: user
          resources:
            limits:
              memory: "256Mi"
              cpu: "750m"
---
apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: ms
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30082
  selector:
    app: sales-service